"""add langauge to posts

Revision ID: b85f5b2e0327
Revises: f6d0d4a5a6fc
Create Date: 2020-07-25 14:21:39.807819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b85f5b2e0327'
down_revision = 'f6d0d4a5a6fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('langauge', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'langauge')
    # ### end Alembic commands ###
